[package]
name = "komootgpx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
geo-types = "0.7.12"
gpx = "0.10.0"
regex = "1.10.3"
reqwest = "0.11.24"
serde = "1.0.196"
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ["full"] }
unescape = "0.1.0"
