[package]
name = "komootgpx"
version = "0.1.0"
edition = "2021"
authors = ["Chris Down <chris@chrisdown.name>"]
description = "Get GPX files from Komoot"
repository = "https://github.com/cdown/komootgpx"
readme = "README.md"
keywords = ["gpx", "hiking", "komoot"]
categories = ["command-line-utilities"]
license = "MIT"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.0", features = ["derive"] }
geo-types = "0.7.12"
gpx = "0.10.0"
regex = "1.10.3"
reqwest = "0.11.24"
serde = "1.0.196"
serde_json = "1.0.113"
tokio = { version = "1.36.0", features = ["full"] }
unescape = "0.1.0"
